Vagrant.configure("2") do |config|

    config.vm.box = "generic/alpine319"
    config.vm.box_check_update = false

    config.vm.define "ahenaultS" do |server|
        server.vm.hostname = "ahenaultS"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "libvirt" do |libvirt|
            libvirt.cpus = 2
            libvirt.memory = 2048
        end
        
        server.vm.provision "file", source: "confs", destination: "/home/vagrant/confs"
        server.vm.provision "shell", path: "scripts/server.sh"
	end

end