# if File.exist?('.env')
#   File.readlines('.env').each do |line|
#     # On ignore les lignes vides et les commentaires
#     next if line.strip.empty? || line.start_with?('#')
#     key, value = line.strip.split('=', 2)
#     ENV[key] = value.gsub(/['"]/, '') if key && value
#   end
# end
# In WSL windows
ssh_pub_key_path = File.expand_path(ENV['PATH_ID_RSA_PUB'])

if File.exist?(ssh_pub_key_path)
	ssh_pub_key_path = File.read(ssh_pub_key_path).strip
else
	puts "Warning : SSH key not found at #{ssh_pub_key_path}"
	ssh_pub_key_path = ""
end

Vagrant.configure("2") do |config|
	config.vm.box = ENV['VM_BOX']
	config.vm.box_version = ENV['VM_VERSION_BOX']

	config.vm.provision ENV['SOFT_PROVIDER'], inline: <<-SHELL
		mkdir -p /home/vagrant/.ssh
		echo "#{ssh_pub_key_path}" >> /home/vagrant/.ssh/authorized_keys
		chown -R vagrant:vagrant /home/vagrant/.ssh
		chmod 700 /home/vagrant/.ssh
		chmod 600 /home/vagrant/.ssh/authorized_keys
	SHELL

	config.vm.define "rihoyS" do |server|
		server.vm.hostname = "rihoyS"
		server.vm.network "private_network", ip: ENV['IP_NODE_S']
		server.vm.synced_folder ".", "/vagrant", type: "rsync"

		server.vm.provider ENV['SOFT_PROVIDER'] do |vb|
			vb.memory = ENV['VM_MEMORY_SERVER']
			vb.cpus = ENV['VM_CORE_SERVER']
			vb.name = "rihoyS"
			extern_path = ENV['PATH_VM_LOAD']
			vb.customize ["setproperty", "machinefolder", extern_path]
		end

		# provision extern scripts
		server.vm.provision "shell",
			path: "scripts/install_p1_server.sh",
			args: [ENV['K3S_TOKEN'], ENV['IP_NODE_S']]
	end

	config.vm.define "rihoySW" do |worker|
		worker.vm.hostname = "rihoySW"
		worker.vm.network "private_network", ip: ENV['IP_NODE_SW']
		
		worker.vm.provider ENV['SOFT_PROVIDER'] do |vb|
			vb.memory = ENV['VM_MEMORY']
			vb.cpus = ENV['VM_CORE']
			vb.name = "rihoySW"
			extern_path = ENV['PATH_VM_LOAD']
			vb.customize ["setproperty", "machinefolder", extern_path]
		end

		worker.vm.provision "shell",
			path: "scripts/install_p1_worker.sh",
			args: [ENV['K3S_TOKEN'], ENV['IP_NODE_S'], ENV['IP_NODE_SW']]
	end
TOKEN = File.read(File.expand_path("confs/token", __dir__)).strip

# Vagrant.configure("2") do |config|

#     config.vm.box = "generic/alpine319"
#     config.vm.box_check_update = false

#     # Server machine
#     config.vm.define "ahenaultS" do |server|
#         server.vm.hostname = "ahenaultS"
#         server.vm.network "private_network", ip: "192.168.56.110"

#         server.vm.provider "libvirt" do |libvirt|
#             libvirt.cpus = 2
#             libvirt.memory = 2048
#         end

#         server.vm.provision "shell", path: "scripts/server.sh", args: [TOKEN]
#     end

#     # ServerWorker machine
#     config.vm.define "ahenaultSW" do |worker|
#         worker.vm.hostname = "ahenaultSW"
#         worker.vm.network "private_network", ip: "192.168.56.111"

#         worker.vm.provider "libvirt" do |libvirt|
#             libvirt.cpus = 1
#             libvirt.memory = 512
#         end

#         worker.vm.provision "shell", path: "scripts/worker.sh", args: [TOKEN]
#     end

# end